### ISSUE TITLE
多余图片ova.png占用空间过大

### ISSUE THREAD

**Issue by OaixGnauh** [vondear/RxTool#107]
那个...能把ova.png图片删掉嘛...
直接引用   compile 'com.github.vondear:RxTools:v1.7.7.3'
apk检查大小时发现这个图片占了988.8 KB ...

![qq 20180413112725](https://user-images.githubusercontent.com/15992858/38715495-05f446b0-3f0e-11e8-88aa-d5365d62f226.png)

**Comment by vondear** [comment]
已删除，谢谢提醒
