### ISSUE TITLE
怎么在依赖的时候去掉你的支付宝sdk呀 ，跟我本地的支付宝SDK重复了，编译过不了

### ISSUE THREAD

**Issue by zhangshaobo87** [vondear/RxTool#114]

**Comment by vondear** [comment]
已分成多模块，可选择性集成

**Comment by vondear** [comment]
基于v1.x.x.x版本可以用以下代码
 compile('com.github.vondear:RxTools:v1.7.8.3') {
        exclude group: 'com.alipay.sdk' 
}
