### ISSUE TITLE
怎么使用圆形裁剪？

### ISSUE THREAD

**Issue by changoal** [vondear/RxTool#133]

**Comment by wadewen** [comment]
//设置裁剪窗口是否为椭圆
        options.setCircleDimmedLayer(true);

**Comment by changoal** [comment]
但是这样只是有一个遮罩，并没有裁剪成圆形图片

**Comment by wadewen** [comment]
我是通过修改Glide的RequestOptions；
//从Uri中加载图片 并将其转化成File文件返回
    private File roadImageView(Uri uri, ImageView imageView) {
        RequestOptions options;
        options = new RequestOptions()
                .transforms(new CenterCrop(), new CircleCrop())
                .priority(Priority.HIGH);

**Comment by vondear** [comment]
可以用 glide 加载图片，用 CircleCrop 就可以了
https://github.com/vondear/RxTool/blob/master/RxDemo/src/main/java/com/vondear/rxdemo/activity/ActivityRxPhoto.java#L174-L190

**Comment by vondear** [comment]
`https://github.com/vondear/RxTool/blob/master/RxDemo/src/main/java/com/vondear/rxdemo/activity/ActivityRxPhoto.java#L174-L190`

**Comment by changoal** [comment]
已解决。感谢各位
