### ISSUE TITLE
implementation "com.github.vondear.RxTool:RxUI:v2.0.4"会导致Glide的placeholder（int）方法找不到

### ISSUE THREAD

**Issue by maxiaoxu2017** [vondear/RxTool#142]
项目中添加完implementation "com.github.vondear.RxTool:RxUI:v2.0.4"之后之前的代码Glide.placeholder(int)方法会报找不到这个方法ID，只要不添加就正常，很奇怪。

**Comment by vondear** [comment]
已解决
