### ISSUE TITLE
RxDialogScaleView 加载图片的方法

### ISSUE THREAD

**Issue by wadewen** [vondear/RxTool#143]
RxDialogScaleView 如何加载网络图片

**Comment by maxiaoxu2017** [comment]
我也遇到这个问题，好像加载不了，我用photoview解决了

**Comment by wadewen** [comment]
我找到办法了， 获取gilde加载图片的bitmap，使用 setImage(Bitmap bitmap) 方法。
 mImageListAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {

                SimpleTarget<Bitmap> simpleTarget = new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<?
                            super Bitmap> transition) {
                        RxDialogScaleView rxDialogScaleView = new RxDialogScaleView(mContext);
                        rxDialogScaleView.setImage(resource);
                        rxDialogScaleView.show();
                    }
                };

                Glide.with(mContext)
                        .asBitmap()
                        .load(imglist.get(position).getImageLocation())
                        .into(simpleTarget);

            }
        });
