### ISSUE TITLE
Failed to find byte code for com/lzy/okgo/callback/StringCallback

### ISSUE THREAD

**Issue by xubo5200** [vondear/RxTool#147]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RxDemo:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/lzy/okgo/callback/StringCallback

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
114 actionable tasks: 6 executed, 108 up-to-date

Android studio 3.1.3  gradle 4.4
编译能过，运行就报错，尝试把gradle降到4.1   build降到3.0.1也不行

**Comment by xubo5200** [comment]
哥们 ，不维护下吗，一直运行不了

**Comment by xubo5200** [comment]
@vondear

**Comment by Degageman** [comment]
me too

**Comment by 1143114725** [comment]
Close Instant Run
File->Settings->Build,Execution,Deployment->Instant Run->Enable.......(default enabled)   untick
取消勾选  Instant Run:
设置->build->  Instant Run-> 第一个取消勾选  关闭即使运行机制
