### ISSUE TITLE
几个一块用会出现多个冲突，exclude都exclude不完

### ISSUE THREAD

**Issue by zlcnup** [vondear/RxTool#149]
implementation 'com.github.vondear.RxTool:RxKit:v2.1.4'
implementation 'com.github.vondear.RxTool:RxUI:v2.1.4'
implementation 'com.github.vondear.RxTool:RxFeature:v2.1.4
implementation 'com.github.vondear.RxTool:RxCamera:v2.1.4'

会出现多个冲突，即Program type already present：
com.google.zxing.ChecksumException
com.alipay.a.a.f
net.lingala.zip4j.core.ZipFile
net.lingala.zip4j.core.HeaderReader
......
最后一个exclude不成功。

**Comment by xubo5200** [comment]
@zlcnup com.alipay.a.a.f 这个应该怎么exclude

**Comment by vondear** [comment]
更新至最新版本 2.3.9 即可
