### ISSUE TITLE
自从2.0.4之后，新版本倒入项目成功后，编译会提示错误。

### ISSUE THREAD

**Issue by T-mans** [vondear/RxTool#167]
根据以下提示，似乎是框架内使用的layout文件引入了非法\u0027字符。

AGPBI: {"kind":"error","text":"error: resource color/green_xiaomi (aka com.yantan.hitbus:color/green_xiaomi) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":12}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:leftIconVisibility\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:rightIcon\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:rightIconVisibility\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:titleColor\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:titleSize\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/green_xiaomi (aka com.yantan.hitbus:color/green_xiaomi) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":20}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:ticker_animationDuration\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":58}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource style/TickerTextAppearance (aka com.yantan.hitbus:style/TickerTextAppearance) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":58}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.yantan.hitbus:ticker_animationDuration\u0027 not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":85}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource style/TickerTextAppearance (aka com.yantan.hitbus:style/TickerTextAppearance) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":85}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource drawable/circle_capture (aka com.yantan.hitbus:drawable/circle_capture) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":115}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/brown2 (aka com.yantan.hitbus:color/brown2) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":121}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource drawable/circle_qr_code (aka com.yantan.hitbus:drawable/circle_qr_code) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":141}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/brown2 (aka com.yantan.hitbus:color/brown2) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":147}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource drawable/circle_bar_code (aka com.yantan.hitbus:drawable/circle_bar_code) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":167}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/brown2 (aka com.yantan.hitbus:color/brown2) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":173}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/e (aka com.yantan.hitbus:color/e) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":197}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource drawable/shape_small_round_blue (aka com.yantan.hitbus:drawable/shape_small_round_blue) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":206}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource color/f0 (aka com.yantan.hitbus:color/f0) not found.","sources":[{"file":"/Users/t-man/.gradle/caches/transforms-1/files-1.1/RxFeature-v2.2.7.aar/5a7162796c4c466bd2b80da6a4c2fab3/res/layout/activity_code_tool.xml","position":{"startLine":215}}],"original":"","tool":"AAPT"}

**Comment by vondear** [comment]
删除根目录下的.gradle和.idea文件夹，清除缓存，重新加载

**Comment by vondear** [comment]
在gradle 3.0.0中AAPT2是默认打开的，在项目的gradle.properties中添加android.enableAapt2=false，sync后就编译通过了。

**Comment by T-mans** [comment]
我是直接把多余的依赖都删除了，只依赖了核心java库。我觉得作者可以通过规范写法来避免这些问题的，关闭Aapt2并不是长久的办法。
