### ISSUE TITLE
项目少了好多资源

### ISSUE THREAD

**Issue by lxhtiamo** [vondear/RxTool#172]
Error:(21) error: attribute 'com.vondear.rxfeature.test:leftIconVisibility' not found.
Error:(21) error: attribute 'com.vondear.rxfeature.test:rightIcon' not found.
Error:(21) error: attribute 'com.vondear.rxfeature.test:rightIconVisibility' not found.
Error:(21) error: attribute 'com.vondear.rxfeature.test:title' not found.
Error:(21) error: attribute 'com.vondear.rxfeature.test:titleColor' not found.
Error:(21) error: attribute 'com.vondear.rxfeature.test:titleSize' not found.
Error:(21) error: resource color/green_xiaomi (aka com.vondear.rxfeature.test:color/green_xiaomi) not found.
Error:(59) error: attribute 'com.vondear.rxfeature.test:ticker_animationDuration' not found.
Error:(59) error: resource style/TickerTextAppearance (aka com.vondear.rxfeature.test:style/TickerTextAppearance) not found.
Error:(86) error: attribute 'com.vondear.rxfeature.test:ticker_animationDuration' not found.
Error:(86) error: resource style/TickerTextAppearance (aka com.vondear.rxfeature.test:style/TickerTextAppearance) not found.
Error:(116) error: resource drawable/circle_capture (aka com.vondear.rxfeature.test:drawable/circle_capture) not found.
Error:(122) error: resource color/brown2 (aka com.vondear.rxfeature.test:color/brown2) not found.
Error:(142) error: resource drawable/circle_qr_code (aka com.vondear.rxfeature.test:drawable/circle_qr_code) not found.
Error:(148) error: resource color/brown2 (aka com.vondear.rxfeature.test:color/brown2) not found.
Error:(168) error: resource drawable/circle_bar_code (aka com.vondear.rxfeature.test:drawable/circle_bar_code) not found.
Error:(174) error: resource color/brown2 (aka com.vondear.rxfeature.test:color/brown2) not found.
Error:(198) error: resource color/e (aka com.vondear.rxfeature.test:color/e) not found.
Error:(207) error: resource drawable/shape_small_round_blue (aka com.vondear.rxfeature.test:drawable/shape_small_round_blue) not found.

**Comment by tanzhihao1qaz** [comment]
我也是这个问题

**Comment by 191996411** [comment]
我也是这个问题

**Comment by vondear** [comment]
更新到最新版本 2.3.9 即可
