### ISSUE TITLE
除了RxKit，其他的集成都提示资源文件缺少

### ISSUE THREAD

**Issue by tanzhihao1qaz** [vondear/RxTool#173]
不仅是最新版本，连前几个都是这样是问题

**Comment by tanzhihao1qaz** [comment]
问题解决了，不过我不知道为啥能解决，我说下我的studio配置
01.在progject structure的project里，我把gradle version设为4.4，android plugin version设为3.1.4
02.在app的gradle里，我原来的compileSdkVersion、targetSdkVersion以及依赖的版本都是27，我把那些
     全改成28
03.同步一下就全部能集成了

**Comment by colaly** [comment]
看看你的support依赖有没有导入完全，RxUi框架里面好像有用的相关的依赖，但是在使用的时候并没有注明，可以尝试把demo里面的依赖添加到你的项目中去，看看是否能解决问题

**Comment by colaly** [comment]
> @colaly 我全加了，27是就是不行，郁闷~

我用的28，引用了RxKit，RxUI，结果发现要依赖 implementation 'com.android.support:cardview-v7:28.0.0'这个包

**Comment by yyllm** [comment]
写的牛逼玩意

**Comment by vondear** [comment]
更新至最新版本 2.3.9 即可
