### ISSUE TITLE
\values.xml:21:5-46: AAPT: error: <item> inner element must either be a resource reference or empty.

### ISSUE THREAD

**Issue by live17909** [vondear/RxTool#181]
\values.xml:21:5-46: AAPT: error: <item> inner element must either be a resource reference or empty.

//功能库（Zxing扫描与生成二维码条形码 支付宝 微信）
        implementation "com.github.vondear.RxTool:RxFeature:v2.2.7"

    <item name="split" type="id">false</item>

没人遇到 这个吗？

**Comment by blankfu** [comment]
28版本的bug   请参考，https://stackoverflow.com/questions/52076491/android-inner-element-must-either-be-a-resource-reference-or-empty
![image](https://user-images.githubusercontent.com/24355623/49364091-57dd4a80-f71e-11e8-93b4-8f6d7f3d6518.png)

**Comment by lxy409875745** [comment]
我这边也是遇到同样的问题,这边修改不了错误的item @vondear

**Comment by avenue2013** [comment]
用记事本打开.gradle\caches\transforms-1\files-1.1\RxFeature-v2.2.7.aar\5b096e677dd55f16a81e2217e783855c\res\values\values.xml:3:

改成这个样子
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="about_version_code" type="id"  />
    <item name="auto_focus" type="id"/>
    <item name="complete_password" type="id"/>
    <item name="complete_qrpaword" type="id"/>
    <item name="complete_zhuce" type="id"/>
    <item name="decode" type="id"/>
    <item name="decode_failed" type="id"/>
    <item name="decode_succeeded" type="id"/>
    <item name="encode_failed" type="id"/>
    <item name="encode_succeeded" type="id"/>
    <item name="gridview" type="id"/>
    <item name="launch_product_query" type="id"/>
    <item name="quit" type="id"/>
    <item name="register_phone_edittext" type="id"/>
    <item name="restart_preview" type="id"/>
    <item name="return_scan_result" type="id"/>
    <item name="search_book_contents_failed" type="id"/>
    <item name="search_book_contents_succeeded" type="id"/>
    <item name="split" type="id" />
    <item name="webview" type="id"/>
    <item name="zhuce_title" type="id"/>
    <string name="app_name">RxFeature</string>
</resources>`

**Comment by yanhu0614** [comment]
> \values.xml:21:5-46: AAPT: error: inner element must either be a resource reference or empty.
> 
> //功能库（Zxing扫描与生成二维码条形码 支付宝 微信）
> implementation "com.github.vondear.RxTool:RxFeature:v2.2.7"
> 
> ```
> <item name="split" type="id">false</item>
> ```
> 没人遇到 这个吗？

我也遇到了

**Comment by vondear** [comment]
更新至最新版本 2.3.9 即可
