### ISSUE TITLE
引入2.2.7UI库后，报错

### ISSUE THREAD

**Issue by QianHong** [vondear/RxTool#187]
![py rb8h9st8i 859 6e6r](https://user-images.githubusercontent.com/22974738/50579320-f4f6e480-0e7e-11e9-895a-1602f971c330.png)

**Comment by agou66** [comment]
我和你一样 你是升级了！Android studio吗 ？同求

**Comment by 17722525963** [comment]
![image](https://user-images.githubusercontent.com/17588070/54908320-93e12900-4f22-11e9-8aab-38e2d5881360.png)

**Comment by 17722525963** [comment]
我也报错~ 求大佬帮助 ~

**Comment by yanxiaonuo** [comment]
我是开新项目后，将RxTool作为Module导入，然后就没报错了

**Comment by vondear** [comment]
更新至最新版 2.3.9 即可
