### ISSUE TITLE
修改一个bug Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by androidscx** [vondear/RxTool#193]
![H%CR `A(MPA03550`T@OR`R](https://user-images.githubusercontent.com/23235068/55538410-fab7cc80-56f0-11e9-8f35-f6b9a6b38d72.png)

60行 改成
  if(Build.VERSION.SDK_INT >= 26){
                c.clipRect(mClipBounds);
            }else {
                c.clipRect(mClipBounds, Region.Op.UNION);
            }
即可

**Comment by vondear** [comment]
收到，谢谢提醒
