### ISSUE TITLE
单依赖UI库报错

### ISSUE THREAD

**Issue by XinHaoLeo** [vondear/RxTool#194]
报错信息：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\RxUI-v2.2.7.aar\bff87a007b2f2f1abf97873ce4f6f735\res\layout\card_item_picture.xml:11: error: attribute cardCornerRadius () not found.
  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\RxUI-v2.2.7.aar\bff87a007b2f2f1abf97873ce4f6f735\res\layout\card_item_picture.xml:11: error: attribute cardElevation () not found.
  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\RxUI-v2.2.7.aar\bff87a007b2f2f1abf97873ce4f6f735\res\layout\card_item_picture.xml:11: error: attribute cardPreventCornerOverlap () not found.
  error: failed linking file resources.

**Comment by MitchZhang** [comment]
和你的报错一样单依赖报错 
AGPBI: {"kind":"error","text":"error: attribute \u0027com.fucang.onetoone:cardCornerRadius\u0027 not found.","sources":[{"file":"/Users/mitchzhang/.gradle/caches/transforms-1/files-1.1/RxUI-v2.2.7.aar/8099eee21f2419e3cf137e5958a0a43e/res/layout/card_item_picture.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.fucang.onetoone:cardElevation\u0027 not found.","sources":[{"file":"/Users/mitchzhang/.gradle/caches/transforms-1/files-1.1/RxUI-v2.2.7.aar/8099eee21f2419e3cf137e5958a0a43e/res/layout/card_item_picture.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.fucang.onetoone:cardPreventCornerOverlap\u0027 not found.","sources":[{"file":"/Users/mitchzhang/.gradle/caches/transforms-1/files-1.1/RxUI-v2.2.7.aar/8099eee21f2419e3cf137e5958a0a43e/res/layout/card_item_picture.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}

**Comment by sbwhy** [comment]
Android resource linking failed
Output:  C:\Users\dell\.gradle\caches\transforms-1\files-1.1\RxUI-2.3.9.aar\abbb7e4403223fa6cb58befc85129706\res\layout\card_item_picture.xml:11: error: attribute cardCornerRadius (aka com.xzyl.cpr:cardCornerRadius) not found.
C:\Users\dell\.gradle\caches\transforms-1\files-1.1\RxUI-2.3.9.aar\abbb7e4403223fa6cb58befc85129706\res\layout\card_item_picture.xml:11: error: attribute cardElevation (aka com.xzyl.cpr:cardElevation) not found.
C:\Users\dell\.gradle\caches\transforms-1\files-1.1\RxUI-2.3.9.aar\abbb7e4403223fa6cb58befc85129706\res\layout\card_item_picture.xml:11: error: attribute cardPreventCornerOverlap (aka com.xzyl.cpr:cardPreventCornerOverlap) not found.
error: failed linking file resources.
同样报错
