### ISSUE TITLE
ZbarManager 是否能支持64位(arm64-v8a)的so文件？

### ISSUE THREAD

**Issue by developer-zsg** [vondear/RxTool#205]
看了一下歷史問題：
libzbar.so is 32-bit instead of 64-bit
https://github.com/vondear/RxTool/issues/30

好像並沒有得到回答，固從新提出此問題。希望能抽空解答一下(因 google Play 應用市場規定2019年8月1日後所有上傳到其市場的app必須支持64位cpu)。

盼復！！！

**Comment by developer-zsg** [comment]
經過自己的努力找到了zbar的源碼和ZbarManager源碼中的decode源碼。結合編譯成功了所有cpu類型的so文件。需要的可以聯繫本人。

**Comment by Runtime007** [comment]
> 經過自己的努力找到了zbar的源碼和ZbarManager源碼中的decode源碼。結合編譯成功了所有cpu類型的so文件。需要的可以聯繫本人。

您好能发一份so文件么 全平台支持的 32位 64位的

**Comment by zhanshao** [comment]
> 經過自己的努力找到了zbar的源碼和ZbarManager源碼中的decode源碼。結合編譯成功了所有cpu類型的so文件。需要的可以聯繫本人。

你好，能否发一份您编译好的so文件呢，多谢

**Comment by developer-zsg** [comment]
> > 經過自己的努力找到了zbar的源碼和ZbarManager源碼中的decode源碼。結合編譯成功了所有cpu類型的so文件。需要的可以聯繫本人。
> 
> 你好，能否发一份您编译好的so文件呢，多谢

給你
[zbar-so.zip](https://github.com/Tamsiree/RxTool/files/7480122/zbar-so.zip)

**Comment by Runtime007** [comment]
thanks

张先森 ***@***.***> 于2021年11月5日周五 上午10:42写道：
