### ISSUE TITLE
RxImageTool中的getRotateDegree（）方法有一个case穿透的问题

### ISSUE THREAD

**Issue by XieYiGod** [vondear/RxTool#73]
你好，  在default后面没有break
switch (orientation) {
                default:
                case ExifInterface.ORIENTATION_ROTATE_90:
                    degree = 90;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_180:
                    degree = 180;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_270:
                    degree = 270;
                    break;
            }

**Comment by xuanxuandaoren** [comment]
谢谢，不过 你是不是发错了

在 2018-01-03 16:41:46，"Ming" <notifications@github.com> 写道：


你好， 在default后面没有break
switch (orientation) {
default:
case ExifInterface.ORIENTATION_ROTATE_90:
degree = 90;
break;
case ExifInterface.ORIENTATION_ROTATE_180:
degree = 180;
break;
case ExifInterface.ORIENTATION_ROTATE_270:
degree = 270;
break;
}
